from flask import Flask, jsonify, request, render_template
import google.generativeai as genai

app = Flask(__name__)

genai.configure(api_key="AIzaSyCoAgRAq6aTzfp7vLkG3el8aKA6C5j5J48")

model = genai.GenerativeModel('gemini-2.0-flash')

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/brainrot')
def generate_brainrot():
    user_prompt = request.args.get('prompt')
    if user_prompt:
        prompt = f"Transform the following text into brainrot with the same amount of sentences from the input using these words (Skibidi – A reference to the “Skibidi Toilet” meme, representing absurdity and humor; Rizz – Slang for having charm or charisma, especially in a dating context; Fanum Tax – The concept of sharing or “taxing” friends by asking for a portion of their belongings; Sigma – Refers to a person, often male, who is a “lone wolf” with strong individualistic qualities; NPC – Means “non-playable character,” implying someone is acting robotic or mindlessly; Cap – Used to call out lies or exaggerations; if something is true, it’s “no cap”; Gyatt – An expression of surprise or admiration, often over someone’s looks; Ratioed – Occurs when a reply or comment gets more likes than the original post, implying disagreement; POV – Stands for “point of view,” a trend where videos depict situations from a particular angle; Sus – Short for “suspicious,” often used when someone acts strangely; Finsta – Fake Instagram account used for close friends, not for public viewing; FYP – TikTok’s “For You Page,” where users find personalized content; Simp – Refers to someone who shows excessive affection for someone they admire; Stan – A combination of “stalker” and “fan,” meaning a dedicated supporter; Yeet – A word that signifies throwing or excitement, often dramatically; Bussin – Used to describe something particularly good or delicious; Flex – Showing off, usually used in the context of possessions or achievements; Thirst Trap – A photo or video intended to attract attention or admiration; Ghosting – The act of suddenly cutting off communication without explanation; Clout – Refers to influence or fame, often linked with social media success; Glow-Up – Describes a transformation, typically a positive physical change; Cancel – When someone is “canceled,” they are publicly called out or boycotted; Tea – Refers to gossip or juicy information; Low-Key – Doing something subtly or in a downplayed manner; High-Key – The opposite of low-key, meaning obvious or open about something; Savage – Describes a bold or unapologetic person or comment; Ship – Short for “relationship,” used when hoping two people will get together; Triggered – Used when someone is annoyed or angered by something specific; Main Character – Describes someone who acts as though they’re the hero of their own story; Cancel Culture – The phenomenon of publicly shaming people on social media.) When using these words, do not highlight them, act like they are a normal part of the text. Also, do not do any POVs. This is meant to also be helpful for kids who only know Gen Z language to learn. And please don't make paragraphs for no reason. If it's just one sentence, keep it a sentence. You also don't need to use every single brainrot word, just the ones tht fit the context. Also don't make it long for no reason!: {user_prompt}"
    else:
        prompt = "Transform the following text into brainrot using these words (Skibidi – A reference to the “Skibidi Toilet” meme, representing absurdity and humor; Rizz – Slang for having charm or charisma, especially in a dating context; Fanum Tax – The concept of sharing or “taxing” friends by asking for a portion of their belongings; Sigma – Refers to a person, often male, who is a “lone wolf” with strong individualistic qualities; NPC – Means “non-playable character,” implying someone is acting robotic or mindlessly; Cap – Used to call out lies or exaggerations; if something is true, it’s “no cap”; Gyatt – An expression of surprise or admiration, often over someone’s looks; Ratioed – Occurs when a reply or comment gets more likes than the original post, implying disagreement; POV – Stands for “point of view,” a trend where videos depict situations from a particular angle; Sus – Short for “suspicious,” often used when someone acts strangely; Finsta – Fake Instagram account used for close friends, not for public viewing; FYP – TikTok’s “For You Page,” where users find personalized content; Simp – Refers to someone who shows excessive affection for someone they admire; Stan – A combination of “stalker” and “fan,” meaning a dedicated supporter; Yeet – A word that signifies throwing or excitement, often dramatically; Bussin – Used to describe something particularly good or delicious; Flex – Showing off, usually used in the context of possessions or achievements; Thirst Trap – A photo or video intended to attract attention or admiration; Ghosting – The act of suddenly cutting off communication without explanation; Clout – Refers to influence or fame, often linked with social media success; Glow-Up – Describes a transformation, typically a positive physical change; Cancel – When someone is “canceled,” they are publicly called out or boycotted; Tea – Refers to gossip or juicy information; Low-Key – Doing something subtly or in a downplayed manner; High-Key – The opposite of low-key, meaning obvious or open about something; Savage – Describes a bold or unapologetic person or comment; Ship – Short for “relationship,” used when hoping two people will get together; Triggered – Used when someone is annoyed or angered by something specific; Main Character – Describes someone who acts as though they’re the hero of their own story; Cancel Culture – The phenomenon of publicly shaming people on social media.) When using these words, do not highlight them, act like they are a normal part of the text. Also, do not do any POVs. This is meant to also be helpful for kids who only know Gen Z language to learn: Lebron James" #Add sample text.
    response = model.generate_content(prompt)
    return jsonify({'brainrot': response.text})

if __name__ == '__main__':
    app.run(debug=True)